# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReportRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, report: str=None):  # noqa: E501
        """ReportRequest - a model defined in Swagger

        :param report: The report of this ReportRequest.  # noqa: E501
        :type report: str
        """
        self.swagger_types = {
            'report': str
        }

        self.attribute_map = {
            'report': 'report'
        }
        self._report = report

    @classmethod
    def from_dict(cls, dikt) -> 'ReportRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The report_request of this ReportRequest.  # noqa: E501
        :rtype: ReportRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def report(self) -> str:
        """Gets the report of this ReportRequest.

        レポートファイルのバイナリデータ  # noqa: E501

        :return: The report of this ReportRequest.
        :rtype: str
        """
        return self._report

    @report.setter
    def report(self, report: str):
        """Sets the report of this ReportRequest.

        レポートファイルのバイナリデータ  # noqa: E501

        :param report: The report of this ReportRequest.
        :type report: str
        """

        self._report = report
