# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReportUploadResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, report_id: str=None):  # noqa: E501
        """ReportUploadResponse - a model defined in Swagger

        :param report_id: The report_id of this ReportUploadResponse.  # noqa: E501
        :type report_id: str
        """
        self.swagger_types = {
            'report_id': str
        }

        self.attribute_map = {
            'report_id': 'report_id'
        }
        self._report_id = report_id

    @classmethod
    def from_dict(cls, dikt) -> 'ReportUploadResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The report_upload_response of this ReportUploadResponse.  # noqa: E501
        :rtype: ReportUploadResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def report_id(self) -> str:
        """Gets the report_id of this ReportUploadResponse.

        レポートの識別子  # noqa: E501

        :return: The report_id of this ReportUploadResponse.
        :rtype: str
        """
        return self._report_id

    @report_id.setter
    def report_id(self, report_id: str):
        """Sets the report_id of this ReportUploadResponse.

        レポートの識別子  # noqa: E501

        :param report_id: The report_id of this ReportUploadResponse.
        :type report_id: str
        """

        self._report_id = report_id
