# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.status_event import StatusEvent  # noqa: F401,E501
from swagger_server import util


class StatusRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, port: str=None, _datetime: datetime=None, detect: bool=None, event: List[StatusEvent]=None, report_id: str=None):  # noqa: E501
        """StatusRequest - a model defined in Swagger

        :param port: The port of this StatusRequest.  # noqa: E501
        :type port: str
        :param _datetime: The _datetime of this StatusRequest.  # noqa: E501
        :type _datetime: datetime
        :param detect: The detect of this StatusRequest.  # noqa: E501
        :type detect: bool
        :param event: The event of this StatusRequest.  # noqa: E501
        :type event: List[StatusEvent]
        :param report_id: The report_id of this StatusRequest.  # noqa: E501
        :type report_id: str
        """
        self.swagger_types = {
            'port': str,
            '_datetime': datetime,
            'detect': bool,
            'event': List[StatusEvent],
            'report_id': str
        }

        self.attribute_map = {
            'port': 'port',
            '_datetime': 'datetime',
            'detect': 'detect',
            'event': 'event',
            'report_id': 'report_id'
        }
        self._port = port
        self.__datetime = _datetime
        self._detect = detect
        self._event = event
        self._report_id = report_id

    @classmethod
    def from_dict(cls, dikt) -> 'StatusRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The status_request of this StatusRequest.  # noqa: E501
        :rtype: StatusRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def port(self) -> str:
        """Gets the port of this StatusRequest.

        ドローンポートを識別する値  # noqa: E501

        :return: The port of this StatusRequest.
        :rtype: str
        """
        return self._port

    @port.setter
    def port(self, port: str):
        """Sets the port of this StatusRequest.

        ドローンポートを識別する値  # noqa: E501

        :param port: The port of this StatusRequest.
        :type port: str
        """
        if port is None:
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501

        self._port = port

    @property
    def _datetime(self) -> datetime:
        """Gets the _datetime of this StatusRequest.

        立入り検知の日時  # noqa: E501

        :return: The _datetime of this StatusRequest.
        :rtype: datetime
        """
        return self.__datetime

    @_datetime.setter
    def _datetime(self, _datetime: datetime):
        """Sets the _datetime of this StatusRequest.

        立入り検知の日時  # noqa: E501

        :param _datetime: The _datetime of this StatusRequest.
        :type _datetime: datetime
        """
        if _datetime is None:
            raise ValueError("Invalid value for `_datetime`, must not be `None`")  # noqa: E501

        self.__datetime = _datetime

    @property
    def detect(self) -> bool:
        """Gets the detect of this StatusRequest.

        立入り状態の代表値  # noqa: E501

        :return: The detect of this StatusRequest.
        :rtype: bool
        """
        return self._detect

    @detect.setter
    def detect(self, detect: bool):
        """Sets the detect of this StatusRequest.

        立入り状態の代表値  # noqa: E501

        :param detect: The detect of this StatusRequest.
        :type detect: bool
        """
        if detect is None:
            raise ValueError("Invalid value for `detect`, must not be `None`")  # noqa: E501

        self._detect = detect

    @property
    def event(self) -> List[StatusEvent]:
        """Gets the event of this StatusRequest.

        立入り検知の情報  # noqa: E501

        :return: The event of this StatusRequest.
        :rtype: List[StatusEvent]
        """
        return self._event

    @event.setter
    def event(self, event: List[StatusEvent]):
        """Sets the event of this StatusRequest.

        立入り検知の情報  # noqa: E501

        :param event: The event of this StatusRequest.
        :type event: List[StatusEvent]
        """
        if event is None:
            raise ValueError("Invalid value for `event`, must not be `None`")  # noqa: E501

        self._event = event

    @property
    def report_id(self) -> str:
        """Gets the report_id of this StatusRequest.

        レポートファイルの識別子  # noqa: E501

        :return: The report_id of this StatusRequest.
        :rtype: str
        """
        return self._report_id

    @report_id.setter
    def report_id(self, report_id: str):
        """Sets the report_id of this StatusRequest.

        レポートファイルの識別子  # noqa: E501

        :param report_id: The report_id of this StatusRequest.
        :type report_id: str
        """

        self._report_id = report_id
